name: Docker Build and Push

on:
  push:
    branches:
      - release
      - feat/add-docker-build-workflow

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-24.04-arm
    environment: production
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Get short SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-2' }}

      - name: Log into ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3.8.0
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.0

      - name: Build and push image
        uses: docker/build-push-action@v5.4.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY || 'yellowstone-grpc-kafka' }}:${{ steps.sha.outputs.SHORT_SHA }}
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max